# -*- coding: utf-8 -*-
"""14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XitoFdFaotRhVff2Sju8ZItosqH1MS2O
"""

import numpy as np

poly = [float(x) for x in input().split()]
x = float(input())
print(np.polyval(poly, x))

