# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7pSZ94kJ8R9CU2Z8mLAVGAmXAz0_Wg_
"""

my_string = "Hello, World!"
print(my_string)