# -*- coding: utf-8 -*-
"""5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17RaNumUlCo0m1a59zpmMaBBUOY_lO1DR
"""

if __name__ == '__main__':
    n = int(input())
    for i in range(0, n):
        print(i ** 2)

3