# -*- coding: utf-8 -*-
"""6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17RaNumUlCo0m1a59zpmMaBBUOY_lO1DR
"""

def is_leap(year):
    leap = False
    
    if (year % 400 == 0):
        return True
    if (year % 100 == 0):
        return leap
    if (year % 4 == 0):
        return True
    else:
        return False
    
    return leap

year = int(input())

print(is_leap(year))