# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6NnTBMip1fF6ugRVodskM3CQhljVM94
"""

regex_pattern = r'[.,]+'    # Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

