# -*- coding: utf-8 -*-
"""5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6NnTBMip1fF6ugRVodskM3CQhljVM94
"""

import math
a = int(input())
b = int(input())
m = int(input())
c = math.pow(a, b)
d = c%m
print(int(c))
print(int(d))

