# -*- coding: utf-8 -*-
"""6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6NnTBMip1fF6ugRVodskM3CQhljVM94
"""

a = int(input())
b = int(input())
c = int(input())
d = int(input())
print((a**b)+(c**d))

