# -*- coding: utf-8 -*-
"""7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6NnTBMip1fF6ugRVodskM3CQhljVM94
"""

for i in range(1, int(input())):
    print((10**(i)//9)*i)

