# -*- coding: utf-8 -*-
"""10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H6NnTBMip1fF6ugRVodskM3CQhljVM94
"""

n = int(input())
s = set([])
for i in range(n):
    s.add(input())
print(len(s))

